name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - alpha

jobs:
  publish-windows:
    runs-on: windows-latest
    steps:
      - name: Fail if branch is not alpha
        if: github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/alpha'
        run: |
          echo "Since app is in early development, we're only releasing on alpha branch until further notice."
          exit 1
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: install dependencies
        shell: bash
        run: yarn --network-timeout 300000
      - name: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: yarn semantic-release
